export const links = [
  {
    name: "Dashboard",
    href: "/",
    icon: "/images/dashboard.svg",
    icon2: "/images/home.svg",
  },

  {
    name: "License approval",
    href: "/license",
    icon: "/images/color-swatch.svg",
    icon2: "/images/swatch.svg",
  },
];
export const paymentHistory = [
  {
    id: 1,
    name: "License activation",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "active",
    created_at: "Sep 4, 2021 at 12:14 am",
  },
  {
    id: 2,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "pending",
    created_at: "Oct 13, 2023 at 08:05 am",
  },
  {
    id: 3,
    name: "Payment for Penalties",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "pending",
    created_at: "Mar 13, 2023 at 08:05 am",
  },
  {
    id: 4,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "success",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 5,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "success",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 6,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "success",
    created_at: "Aug 3, 2023 at 12:10 am",
  },
  {
    id: 7,
    name: "License renewal",
    plate_number: "REF6478394HG",
    amount: "N120,000",
    status: "success",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
];
export const riders = [
  {
    id: 1,
    name: "Israel Faizul",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "active",
    created_at: "Sep 4, 2021 at 12:14 am",
  },
  {
    id: 2,
    name: "Daniel Samuel",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "deleted",
    created_at: "Oct 13, 2023 at 08:05 am",
  },
  {
    id: 3,
    name: "Josh Michael",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "active",
    created_at: "Mar 13, 2023 at 08:05 am",
  },
  {
    id: 4,
    name: "Ebubechukwu Agnes",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "unlinked",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 5,
    name: "Solomon Ideh",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "unlinked",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 6,
    name: "Adese Samson",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "unlinked",
    created_at: "Aug 3, 2023 at 12:10 am",
  },
  {
    id: 7,
    name: "Hameed Yusuf",
    plate_number: "REF6478394HG",
    vehicle_type: "motorcycle",
    status: "active",
    created_at: "Jan 1, 2023 at 01:49 pm",
  },
];
export const licenses = [
  {
    id: 1,
    company_name: "KK Logistics",
    company_email: "kklogistics@company.com",
    license_type: "Vehicle",
    license_duration: "1 year",
    status: "Pending",
  },
  {
    id: 2,
    company_name: "GIG",
    company_email: "gig@company.com",
    license_type: "Driver",
    license_duration: "2 years",
    status: "Approved",
  },
  {
    id: 3,
    company_name: "FRS Logistics",
    company_email: "frslogistics@company.com",
    license_type: "Vehicle",
    license_duration: "6 months",
    status: "Pending",
  },
  {
    id: 4,
    company_name: "ABS Transport",
    company_email: "abs@company.com",
    license_type: "Driver",
    license_duration: "1 year",
    status: "Approved",
  },
  {
    id: 5,
    company_name: "SHK Logistics",
    company_email: "shklogistics@company.com",
    license_type: "Vehicle",
    license_duration: "3 years",
    status: "Approved",
  },
  {
    id: 6,
    company_name: "Freeway",
    company_email: "freeway@company.com",
    license_type: "Driver",
    license_duration: "1 year",
    status: "Pending",
  },
  {
    id: 7,
    company_name: "Longtrail",
    company_email: "longtrail@company.com",
    license_type: "Vehicle",
    license_duration: "2 years",
    status: "Approved",
  },
];

export const licensesPending = [
  {
    id: 3,
    name: "License Inspection",
    license_type: "International",
    license_duration: "2 years",
    status: "pending",
    created_at: "Mar 13, 2023 at 08:05 am",
  },
];

export const companies = [
  {
    id: 1,
    company_name: "KK Logistics",
    company_email: "kklogistics@company.com",
    contact_phone: "+234 814 4939 493",
    status: "Pending",
    date_requested: "Sep 4, 2021 at 12:14 am",
  },
  {
    id: 2,
    company_name: "GIG",
    company_email: "gig@company.com",
    contact_phone: "+234 814 1234 567",
    status: "Pending",
    date_requested: "Oct 13, 2023 at 08:05 am",
  },
  {
    id: 3,
    company_name: "FRS Logistics",
    company_email: "frslogistics@company.com",
    contact_phone: "+234 814 2345 678",
    status: "Pending",
    date_requested: "Mar 13, 2023 at 08:05 am",
  },
  {
    id: 4,
    company_name: "ABS Transport",
    company_email: "abs@company.com",
    contact_phone: "+234 814 3456 789",
    status: "Approved",
    date_requested: "Jan 1, 2023 at 01:49 pm",
  },
  {
    id: 5,
    company_name: "SHK Logistics",
    company_email: "shklogistics@company.com",
    contact_phone: "+234 814 4567 890",
    status: "Approved",
    date_requested: "Feb 21, 2023 at 03:05 pm",
  },
  {
    id: 6,
    company_name: "Freeway",
    company_email: "freeway@company.com",
    contact_phone: "+234 814 5678 901",
    status: "Approved",
    date_requested: "Aug 3, 2023 at 12:10 am",
  },
  {
    id: 7,
    company_name: "Longtrail",
    company_email: "longtrail@company.com",
    contact_phone: "+234 814 6789 012",
    status: "Approved",
    date_requested: "Feb 21, 2023 at 03:05 pm",
  },
];
