import { Courier, CouriersResponse } from "@/types/courier";

export const mockCouriers: Courier[] = [
  {
    id: 1,
    uuid: "9f4b67a5-d12e-4fa8-a2a1-a84503788a75",
    name: "Ngozi Inc PLC",
    slug: "ngozi-inc-plc",
    reference: "CLRD-COUR-20250702-1751462102-KUGMFP",
    registration_number: "e0765a9f-d170-4f6b-9e19-207e350b328f",
    phone: "0705976024",
    email: "chinedu.busari@hotmail.com",
    address: "66 Adaobi Street 92 768 AdeboyeVille",
    contact_person: {
      first_name: "Catharine",
      last_name: "Rosenbaum",
      phone: "08082345678",
      email: "Georgianna_Welch@yahoo.com",
      nin: null,
      address: "280 Veum Ford",
      username: "catharine-rosenbaum-gmw",
    },
    webhook_url: null,
    activated_at: "Wed, Jul 16, 2025 4:23 PM",
    profile: {
      applicant_name: "Catharine Rosenbaum",
      applicant_position: "Corporate Integration Consultant",
      business_name: "Ngozi Inc PLC",
      cac_number: "e0765a9f-d170-4f6b-9e19-207e350b328f",
      address: "25235 Fritsch Coves",
      license_category: {
        name: "State/Special SME's",
        description:
          "Numquam deleniti voluptate eaque culpa blanditiis illum. Ut velit voluptatibus fuga numquam atque corporis. Porro molestias voluptatibus quis officiis qui sapiente. Ut natus quidem accusantium dolor voluptatem sed velit.",
        price: "250000.00",
        renewal_price: "100000.00",
      },
      state: {
        id: 25,
        name: "Lagos",
        short_name: "LA",
      },
    },
    activated: true,
    has_active_license_application: true,
    created_at: "Wed, Jul 2, 2025 2:15 PM",
    updated_at: "1 week ago",
    deleted_at: null,
  },
  {
    id: 2,
    uuid: "9f4b67a6-d12e-4fa8-a2a1-a84503788a76",
    name: "Swift Logistics Ltd",
    slug: "swift-logistics-ltd",
    reference: "CLRD-COUR-20250703-1751462103-KUGMFP",
    registration_number: "e0765a9f-d170-4f6b-9e19-207e350b328g",
    phone: "08012345678",
    email: "info@swiftlogistics.com",
    address: "123 Business Avenue, Victoria Island",
    contact_person: {
      first_name: "John",
      last_name: "Doe",
      phone: "09087654321",
      email: "john.doe@swiftlogistics.com",
      nin: "12345678901",
      address: "456 Main Street, Lagos",
      username: "john-doe-swift",
    },
    webhook_url: "https://swiftlogistics.com/webhook",
    activated_at: "Thu, Jul 17, 2025 3:30 PM",
    profile: {
      applicant_name: "John Doe",
      applicant_position: "CEO",
      business_name: "Swift Logistics Ltd",
      cac_number: "RC123456",
      address: "123 Business Avenue, Victoria Island, Lagos",
      license_category: {
        name: "National Courier",
        description: "National courier services license",
        price: "500000.00",
        renewal_price: "200000.00",
      },
      state: {
        id: 25,
        name: "Lagos",
        short_name: "LA",
      },
    },
    activated: true,
    has_active_license_application: false,
    created_at: "Thu, Jul 3, 2025 10:30 AM",
    updated_at: "2 days ago",
    deleted_at: null,
  },
  {
    id: 3,
    uuid: "9f4b67a7-d12e-4fa8-a2a1-a84503788a77",
    name: "Express Delivery Co",
    slug: "express-delivery-co",
    reference: "CLRD-COUR-20250704-1751462104-KUGMFP",
    registration_number: "e0765a9f-d170-4f6b-9e19-207e350b328h",
    phone: "07098765432",
    email: "contact@expressdelivery.com",
    address: "789 Delivery Street, Ikeja",
    contact_person: {
      first_name: "Sarah",
      last_name: "Johnson",
      phone: "08123456789",
      email: "sarah.johnson@expressdelivery.com",
      nin: "98765432109",
      address: "321 Oak Avenue, Ikeja",
      username: "sarah-johnson-express",
    },
    webhook_url: null,
    activated_at: null,
    profile: {
      applicant_name: "Sarah Johnson",
      applicant_position: "Operations Manager",
      business_name: "Express Delivery Co",
      cac_number: "RC789012",
      address: "789 Delivery Street, Ikeja, Lagos",
      license_category: {
        name: "Local Courier",
        description: "Local courier services license",
        price: "150000.00",
        renewal_price: "75000.00",
      },
      state: {
        id: 25,
        name: "Lagos",
        short_name: "LA",
      },
    },
    activated: false,
    has_active_license_application: true,
    created_at: "Fri, Jul 4, 2025 9:15 AM",
    updated_at: "1 day ago",
    deleted_at: null,
  },
];

export const mockCouriersResponse: CouriersResponse = {
  status: "success",
  message: "Couriers retrieved successfully.",
  data: {
    meta: {
      total: 3,
      per_page: 100,
      current_page: 1,
      last_page: 1,
      first_page_url: "http://clrd_accounts.test/api/v1/admin/couriers?page=1",
      last_page_url: "http://clrd_accounts.test/api/v1/admin/couriers?page=1",
      next_page_url: null,
      prev_page_url: null,
      path: "http://clrd_accounts.test/api/v1/admin/couriers",
      from: 1,
      to: 3,
    },
    couriers: mockCouriers,
  },
};
